import { SocializationCategory } from '@/types/socialization';

export const defaultSocializationCategories: SocializationCategory[] = [
  {
    id: 'visual-noises',
    name: 'Visual & Noises',
    items: [
      { id: 'sirens', name: 'Sirens', completed: false },
      { id: 'fireworks', name: 'Fireworks', completed: false },
      { id: 'car-horns', name: 'Car horns', completed: false },
      { id: 'traffic', name: 'Traffic', completed: false },
      { id: 'thunderstorms', name: 'Thunderstorms', completed: false },
      { id: 'fairs-festivals', name: 'Fairs and festivals', completed: false },
      { id: 'shopping-malls', name: 'Shopping malls', completed: false },
      { id: 'busy-traffic', name: 'Busy traffic', completed: false },
      { id: 'crowds', name: 'Crowds of people', completed: false },
      { id: 'airplanes', name: 'Airplanes', completed: false },
      { id: 'helicopters', name: 'Helicopters', completed: false },
      { id: 'wheelchairs', name: 'Wheelchairs', completed: false },
      { id: 'crutches-canes', name: 'Crutches/canes', completed: false },
      { id: 'bicycles', name: 'Bicycles', completed: false },
      { id: 'skateboards', name: 'Skateboards', completed: false },
      { id: 'radios-loud-cars', name: 'Radios, loud cars', completed: false },
      { id: 'motorbikes', name: 'Motorbikes', completed: false },
      { id: 'parking-lots', name: 'Parking lots', completed: false },
      { id: 'door-bells', name: 'Door bells', completed: false },
      { id: 'knocking-doors', name: 'Knocking on doors', completed: false },
      { id: 'trucks', name: 'Trucks', completed: false },
      { id: 'trains', name: 'Trains', completed: false },
    ],
  },
  {
    id: 'places',
    name: 'Places',
    items: [
      { id: 'veterinarians', name: 'Veterinarians', completed: false },
      { id: 'boarding-kennels', name: 'Boarding kennels', completed: false },
      { id: 'daycare', name: 'Daycare', completed: false },
      { id: 'pet-shop', name: 'Pet shop', completed: false },
    ],
  },
  {
    id: 'maneuver-touch',
    name: 'Maneuver & Touch',
    items: [
      { id: 'stairs', name: 'Stairs', completed: false },
      { id: 'escalators', name: 'Escalators', completed: false },
      { id: 'tile', name: 'Tile', completed: false },
      { id: 'marble', name: 'Marble', completed: false },
      { id: 'asphalt-concrete', name: 'Asphalt, concrete', completed: false },
      { id: 'grass', name: 'Grass', completed: false },
      { id: 'sand', name: 'Sand', completed: false },
      { id: 'carpet', name: 'Carpet', completed: false },
      { id: 'wood', name: 'Wood', completed: false },
      { id: 'smell', name: 'Smell', completed: false },
    ],
  },
  {
    id: 'interacting-people',
    name: 'Interacting with People',
    items: [
      { id: 'holding-puppy', name: 'Holding puppy', completed: false },
      { id: 'touching-paws', name: 'Touching paws', completed: false },
      { id: 'touching-muzzle', name: 'Touching muzzle', completed: false },
      { id: 'touching-ears', name: 'Touching ears', completed: false },
      { id: 'touching-tail', name: 'Touching tail', completed: false },
      { id: 'hugging-puppy', name: 'Hugging puppy', completed: false },
      { id: 'touching-collar', name: 'Touching collar', completed: false },
      { id: 'checking-teeth', name: 'Checking teeth', completed: false },
      { id: 'clipping-nails', name: 'Clipping nails', completed: false },
      { id: 'brushing-teeth', name: 'Brushing teeth', completed: false },
      { id: 'checking-pads', name: 'Checking between pads', completed: false },
      { id: 'cleaning-ears', name: 'Cleaning ears', completed: false },
      { id: 'touching-rear-legs', name: 'Touching rear legs', completed: false },
      { id: 'brushing-grooming', name: 'Brushing/grooming', completed: false },
    ],
  },
  {
    id: 'meeting-people',
    name: 'Meeting People',
    items: [
      // Men with
      { id: 'men-beards', name: 'Men with beards', completed: false },
      { id: 'men-hats', name: 'Men with hats', completed: false },
      { id: 'men-sunglasses', name: 'Men with sunglasses', completed: false },
      { id: 'men-jewelry', name: 'Men with jewelry', completed: false },
      { id: 'men-helmets', name: 'Men with helmets', completed: false },
      { id: 'men-cigarettes', name: 'Men with cigarettes', completed: false },
      // Women with
      { id: 'women-hats', name: 'Women with hats', completed: false },
      { id: 'women-sunglasses', name: 'Women with sunglasses', completed: false },
      { id: 'women-jewelry', name: 'Women with jewelry', completed: false },
      { id: 'women-helmets', name: 'Women with helmets', completed: false },
      // Children
      { id: 'children-0-2', name: 'Children 0-2 years', completed: false },
      { id: 'children-strollers', name: 'Children in strollers', completed: false },
      { id: 'children-2-4', name: 'Children 2-4 years old', completed: false },
      { id: 'children-4-12', name: 'Children 4-12 years old', completed: false },
      { id: 'children-13-19', name: 'Children 13-19 years old', completed: false },
      // Adults with
      { id: 'adults-crutches', name: 'Adults with crutches', completed: false },
      { id: 'adults-canes', name: 'Adults with canes', completed: false },
      { id: 'adults-wheelchairs', name: 'Adults with wheelchairs', completed: false },
      // Elderly
      { id: 'elderly-male', name: 'Elderly person (male)', completed: false },
      { id: 'elderly-female', name: 'Elderly person (female)', completed: false },
    ],
  },
  {
    id: 'people-sounds',
    name: 'People Sounds',
    items: [
      { id: 'talking-loudly', name: 'Talking loudly', completed: false },
      { id: 'laughing', name: 'Laughing', completed: false },
      { id: 'crying', name: 'Crying', completed: false },
      { id: 'shouting', name: 'Shouting', completed: false },
      { id: 'arguing', name: 'Arguing', completed: false },
      { id: 'children-playing', name: 'Children playing', completed: false },
    ],
  },
  {
    id: 'meeting-animals',
    name: 'Meeting Animals',
    items: [
      { id: 'puppies', name: 'Puppies', completed: false },
      { id: 'male-adult-dogs', name: 'Male adult dogs', completed: false },
      { id: 'female-adult-dogs', name: 'Female adult dogs', completed: false },
      { id: 'kittens', name: 'Kittens', completed: false },
      { id: 'cats', name: 'Cats', completed: false },
      { id: 'horses', name: 'Horses', completed: false },
      { id: 'cow', name: 'Cow', completed: false },
      { id: 'sheep', name: 'Sheep', completed: false },
      { id: 'chickens', name: 'Chickens', completed: false },
      { id: 'ducks', name: 'Ducks', completed: false },
    ],
  },
];
